spring.application.name=quiz-system


spring.datasource.url=jdbc:postgresql://dpg-d82914ugvqtc73dg3e50-a.oregon-postgres.render.com:5432/mydb_jh2h?sslmode=require
spring.datasource.username=mydb_jh2h_user
spring.datasource.password=1SelwY0sb3vyJ3BGA3PClZF34l4O4pq2
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=mySecretKeyForJWTTokenGenerationWhichShouldBeLongEnough256Bits
jwt.expiration=86400000

server.port=8081